version: "3.9"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - gh_example_bundle:/usr/local/bundle
    depends_on:
      - db

volumes:
  gh_example_bundle:
  mysql-data:
