name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ruby: [ '2.3', '2.4' ]

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run : bundle install
      - name: Create database
        run: |
          mysql -uroot -h 127.0.0.1 -e "DROP DATABASE IF EXISTS ghactions_test;"
          mysql -uroot -h 127.0.0.1 -e "CREATE DATABASE ghactions_test;"
      - name: query database with mysql2
        run: |
          bundle exec ruby -e "require 'mysql2'; results = Mysql2::Client.new(:host => '127.0.0.1', :username => 'root', :database => 'ghactions_test').query('SELECT table_name from information_schema.tables;');"
